# Generated by Django 5.1 on 2024-09-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
