# Generated by Django 5.1.1 on 2024-09-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='opt',
            new_name='otp',
        ),
    ]
